pipeline{

agent {
  label 'DevServer'
}
parameters {
  string defaultValue: 'bob', name: 'LASTNAME'
}
environment{
    NAME = "Jenkins"
}
tools {
  maven 'mymaven'
}
    stages{
        stage('build')
        {
            steps
            {
                sh 'mvn clean package'
                echo "hello $NAME ${params.LASTNAME}"
            }

            post {
                success {
                    archiveArtifacts artifacts: '**'
                }
            }
        }
    }
}
