pipeline{

agent {
  label 'DevServer'
}
parameters {
  string defaultValue: 'bob', name: 'LASTNAME'
}
environment{
    NAME = "Jenkins"
}
tools {
  maven 'mymaven'
}
    stages{
        stage('build')
        {
            steps
            {
                sh 'mvn clean package'
                echo "hello $NAME ${params.LASTNAME}"
            }

        }
        stage('test')
        {
            parallel
            {
                stage('testA')
                {
                    steps{
                    echo 'This is test A'
                    }
                }
                stage('testB')
                {
                    steps{
                    echo 'This is test B's
                    }
                }
            }
            post {
                success {
                    archiveArtifacts artifacts: '**'
                }
            }
        }
    }
}
