pipeline{

agent {
  label 'DevServer'
}
agent any
    stages{
        stage('build')
        {
            steps
            {
                sh 'mvn clean package'
            }

            post {
                success {
                    archiveArtifacts artifacts: '**/target/*.war'
                }
            }
        }
    }
}
